Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "StorageServer#{i}" do |node|
      node.vm.hostname = "StorageServer#{i}"
      node.vm.box = "ubuntu/xenial64"
      node.vm.box_check_update = false
      node.vm.network "private_network", ip: "192.168.1.118:525#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      node.vm.network "public_network", bridge: "zat1"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "storages#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      node.vm.provision "shell", path: "provision.sh", privileged: false
    end
    # config.ssh.insert_key = false
  end
end
