# Membuat Storage Server
Vagrant.configure("2") do |config|
  config.vm.define "StorageServer" do |storage_server|
    storage_server.vm.hostname = "StorageServer"
    storage_server.vm.box = "ubuntu/xenial64"
    storage_server.vm.network "private_network", ip: "192.168.1.118"
    storage_server.vm.network "public_network", bridge: "zattraft"
    
    storage_server.vm.provider "virtualbox" do |vb|
      vb.name = "StorageServer"
      vb.gui = false
      vb.memory = "1024"
    end
    storage_server.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-setuptools python3-dev
    apt-get install -y python3-pip
    SHELL
    storage_server.vm.provision "shell", path: "zatt_install.sh", privileged: false
  end

# Membuat Storage Service Node
(1..3).each do |i|
  config.vm.define "StorageService#{i}" do |service_node|
    service_node.vm.hostname = "ServiceNode#{i}"
    service_node.vm.box = "ubuntu/xenial64"
    service_node.vm.box_check_update = false
    service_node.vm.network "private_network", ip: "192.168.1.11#{i}"
    service_node.vm.network "public_network", bridge: "zattraft"

    service_node.vm.provider "virtualbox" do |vb|
      vb.name = "ServiceNode#{i}"
      vb.gui = false
      vb.memory = "512"
    end
    storage_server.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-setuptools python3-dev
    sudo python3 /zatt/setup.py install
    SHELL
    service_node.vm.provision "shell", path: "run_zatt.sh", privileged: false
  end
end
